---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBoo8irehEJ6ma15B4J3Oj4t48IcLm2cwYlihx37EBkL/6IKbrJQlL6dWMv0dCfkkA/ACOqPX60jW5ivsnGDvPytDRbHEXQhLJaHzE50bVTDzjUs2X3432uVpYhNHEh+Bax5Iiy3nfu5QtG/p76VAjzq/r7U6ER8aF4MMHY5h5Bap4i/bnHsSkPlNvByp8fChzF51995qPniotGBTN3r2tAWxA6HsbH98tUaWkbqcCzg5vzyprcieh6pwaUdQyesCvflwwyeY2hOeeZ9Pob9YJLPtd8gVrdTIkrmSl0kDheBQuFXNDvp43yJKhEVy7sMabnUGeDqoL7XHLiQtLy8jFZDaXEFQM0YSoiHwTd+97l7/n1brIdH4K2PPHIh0HNMs8475REzU9BzKAuXh1b9o+n45mMSI2YIC6QG5NK6j1bmdAcfxMq8fdwZAyUco7JGKJYQ1hUjV2wuaUxzp+H7o+T8TVIr7gSXM3ASkqxWSMNMDiHny4H9kshyTCfKF4Hz6rlgjiW/IYv0YJcfijCjIWZb17XgBMzWKxXkrkGC4gXJmgdbn5cSjc0nFy+3RyWMeTcMZOeXR7KLhc51cPq4w0ZFNijC0q9z+G3lQRpjjVNS17i93W1c7eP2t4rTs77gVCnTTWxbU1AQNMVOpYkJRVWwPxoaaSaeBnE6VmG5cO+c5AzFkD7dUsSIu4Kj7Jbz5Fp4bFQoRyTLUlt48xQuRhNEjy7hDHvszSGih115PFItXVOthkracWBEYx17mHFnMUBGjuJVA9ejna1h5zyMsRK
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
