apiVersion: v1
kind: Namespace
metadata:
  annotations:
    iam.amazonaws.com/allowed-roles: |
      ["arn:aws:iam::438423213058:role/sealed-secrets-backuper-guilherme-testing"]
  name: sealed-secrets
spec:	
  finalizers:	
    - kubernetes
