apiVersion: v1
kind: Namespace
metadata:
  annotations:
    iam.amazonaws.com/allowed-roles: |
      ["arn:aws:iam::438423213058:role/velero-guilherme-testing"]
  name: velero
spec:	
  finalizers:	
    - kubernetes
