---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgB/5pwYZjb7xShG6gfcFhQla0dR8NxZFp68JIPW44fIpdhMIjtVKCo8HBHnk3QQRw3Jskcs/7xFcs4AtxSS2BGXYHMnvXVyURtdkPRl/adJU7mLM4zJaF1Bb8yrUzLMtYG/tyrDX9wOzImhSET+UJyHUFsbPweoDRUZFSJp20TSSBz6JxbpNUR/S824biY0Pk6FIU4pB0cfmOi2EpWqnG1X7Mhb5jEzPRgLANk79Xld7+arQEIoKZKTUOqbxbbl8u0HXyT1lR/TEf/Zqy2eGhGe0JnLlIVW9zUOObMLtLFCPMNLuJnjmYhHxO45ThY9hg9n4mGWDr03hQz1L+1GDepqlMsihDlq4JRl2fNpxQGdjxrGNRO/+Xmfrpwe6vj1WDSLOy1qmWsj8SgqtzPRD3Y6M6SNICFDrAMi3zcLfkHazwap7z/vmJXfImD0+Ucj1oq7M9Dalt3ndChiV5m//jPd3WUbTF1prcgvEyUjQgvMLBp0odUgfcGZPyXAzmbd+Zg+C2sJ8Ct5VUGl8x3uLbnCwuMbKkXUxMwzwzVimRFCk7+XC+fDeBMboavnXEj7Opi7s0ldQhya6Fc3YgJErbfTZ05uSguVWpVw0aZgEXVYfthk5AyP1ci7SlQPt4kLU9u2SrxCZqyRer8t7ULnMsVzsQoIsgACzRznSPZ/Crke1o/4ZqIiCI3fVCmYz1H28fA+I8xbDFH9wb77nOVHjjgGDGfl6S1DWr6ExUa51v39PVQzWPyNhrCar1KvISRdwqFtLwyoK6srY3hAmjBRi4lH
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
