apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    AWS_B64ENCODED_CREDENTIALS: AgCdWV37lJhhB6KL3rSFuiYTc1GSsaMqzYL/5XF6Tvm6RwDPZmxVMxD2fe71PmK8r0x2YTOJzqdFz4dC+GzwjQ5AXUnUlqWPo85Hn32pJA8zxnZ3w98wY/ekzim4oCnUxZGEQbCDsBIBlCjvYYztpQpLkifUxuxRYdpk5TB2yNpa19B/4uJ388B4pEwAbRB9ayP76KwK1c4a/2XQyQrHUL7IVPL7uP4pdhkyX0rHqsksAQxfhNh1Ah0iXDOXeijY6SYORZGmb7TSYfOJIwnOIRWrOnSeV1Vv99kUqIK/2YOsXl7tqQopsmkERF6E4i8z2N41QfBZDtCD8q6PQz3WHHGOYY7XGcjhR03IJGKrh7PcoZ1xzmhJAqBfOBN3ENWcPRg6FSe2ErXvz49eVRSl7JNLvBT6Z8TN/Io682uyLgELcUyJGmjHQsvykzYypY7P6b+64B00qHP4FpP9my4iCx18sXddRx/SGAWbHRiJmfLvWIPpGfH0Hx0ly5ujrddgrV7qGWyLMeQBuOdkbz2Q10s6GEMcQ3gHGLlvE+n9xO3hOtUrpdOhAeU6VPzCFgTCW6aqGY0DUgEsexkdsTFurMVI/5JLygy5ogCmGYhCJjtxrG2/AxF8dmVJhQ58FEIorLMN/GvVLWzxxE7DtFyW3T5bmXnP2On35rhjtDv03uVM+IZybFPeLWhH2GfguKuvQ30F9g8s9VSy83GO6Mv23DfrchBeG3G0FgOyKlYdbBvEaWReGl03I0BrvXdWvL02B1JjQ99CkbtwGK2KUAt3Rse2PDH3NKMLnPY4RRATK4cmAbV8WWlZOvPmP1ufz7L9a9I5iw7vS6VSCyXDEQtdP42rRElRxSpuocXTJtZLnQkDRQhuDQHqon+7BqpqqHayFHI9mScojV20vDIYx/47D674ZqvpoUbMwZa5BPNSY/upEsljo2ACfn+2
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster

