---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBAxbkiGAx/BLovuPMcVlA5XCaVqEWZy6K0X1c3MRo8wOqGx2TZ+M4X1hNMBPxZKOUGGykWlhkVTq+zzP8i+Z/afY/gQzuc9DX3XMldgktcd5TKfZ3De4ZgFhmeFqLCvbPZuMufeT5+ksIEbQ6A9YdVRJztZ5hZeIlDlG3N1CBnpXCjFpiH8SXAi40vTuIultbb7g3qtCB5/4E44VfqRoYjhE1sISp3gqNU/XowBL56Oteeyqphjtpt3ZuoWGX5XmKpP246tn5A0pMrTHJhDXdr5X2CQLSCK4ti59/pXGiudqOPkzAWi2GTypPi5p2Fu2CQsyg6onqs/y6+pSgiDFMiizpdszYWA6bueLHSC38j48gN7gnvgt7crakA42WamR1Fg6VjwxurcD6W9ZJPBrfKm5DpiquMSln7JoVE8lLcsR5XBa2XaNXuzo3y29hod8PWl9Fp0Qa9Pm89RkJnzRTIVez58CDQZg06ZT2VT9c65EcAb2b7/3xO3F4FHeSx2LnWAbtGSTfn3Zqu4Yn43wcFDfe3UG6jJekJ7vS/xMN7xa55ktk+bAYSzHIRIS8vJFnxLF8Z1kFvwovGcIiP4HfxJCTxvP0WOxvhC56WQqUIbPeW6S1U6WDMQ0TzSfWP0Oy/K91FrCejGMrgpAqjs4gfIXWzt61zlk5pefeAMlxAbBl2kb4/3g+QX3SvoUjCrfmpHsCECX8xXsdDZYsHA23PYs0Buz1RNPDoMEhDG278jGmBw/YezNaiJRny/rd2QbBDlV2wT8gdgO2yZG/qjFCg
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
