apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "10.0.1"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: capi-cluster
  namespace: argo-cd
spec:
  destination:
    namespace: capi-cluster
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/capi-cluster
      targetRevision: 10.0.1
      helm:
        valueFiles:
          - $values/k8s/guilherme-test-capi/argocd-apps/capi-cluster.values.yaml
    - repoURL: https://github.com/guilherme-santos03/capi-test
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
