apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "10.0.1"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: secrets
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: kubeaid
  source:
    path: k8s/guilherme-test-capi/sealed-secrets
    repoURL: https://github.com/guilherme-santos03/capi-test
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy: {}
