---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgCIyF9bXGpkt+tA3AKi0XsvzfDXztmZZ9WQ1AUqu3WHHX8lpqpqTRXC2o3M/XIP01onTbmp9YSTFd24itcE+eht/Zv+UD/+OPnoTFbjwyj7T4BbwncO4YG4vh5cco4NpYbGGalMLtab3ThB5QNdErhonk3pB4PpjrNjyUswX/Sbvt3/oqHeQh37yyUo9D0jSrMJtmrh1kphQD28o1aZxgxj6x9tn5TIxL9gF8n3huA66Ig0x44RTfKpJMF8oFPD0BwsSDAT8XNXdhfuqpgicBwS5EBKnhsCPz7xrgExsmtLGtqjLZTjOB4XJURkZNmgWLwuubXowJfwIip5WmKdUnngusJN1zAZbiEuEvApvIux2fdnsYUDEIAK40IbmKCcNgDNiWBdT7mKJ/PG/gU47B/E64jcWddDvlHzd18mtjMPIhKnXpWxZ6ZUAe59m2uuxbYJxiPgGcR0AyWnuD6Wft1tsyxn1nS16tgAJXN3cRenGpzRZyirNkzFz0O9abT8Z2n9tKTiJpCluJpp8U5DEce7S4EzqU78u5dEB7/wtubCy/XsFi8bpFtey1z5Qjs1puF8izt1XHR0RAAm88ZTTCZgkOaumv35e47So432nbImzC7vDty0Ku2UosPl+A5ouSHycCmC+jxpC8IvObeT/20/KiemQfCrjGegThR59TAe6QyTSEVY4TRCo6lUzACAub1jVYeoNAjRObe3LTocE5a3w6zc/wQIqBOsWmTt20NtdEELnCUMRd5NPgXfumS8vjY6U/aC4Z6UMRY1wbtDRMJs
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
