---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBdYyrYPLbIYVzI9yXivoPY7SdY7X7eAEfHvJNYXaqpr1S1n2ZG1e0xHHiQi13mIJUopB3j6tibYCV1/aGFTP6lv1qz5qxyjkmndQy7WgDgKf+9THHPlMI+NsROhPK8On8xf6Hrhug/Sr679MY/nq3BJIU5eTEsH2Qe11yj1bTqKInaUAlt+iI6ETRuCwh3vikPG94ddGwH3D5G5qOE/o7XLKk/dE840io/xUOGSCiZj3+WVKViL67mfT6lDwwllaUQl43N5Vla2RwQMj4x0RLOu81Ctg1WrYx/mcyT4hoi6snY+B3YK+KVlblAswmNxmg5vfQoNB1VnpxjwX6RQ0EeUD4WxwPSnnni/sC850erfrTrxtduJCEj6rc8ddY9hdRX44E7OJ+EV7PWM98dY50rE8Mhk5g54G1OoYYiUJkSHunULswDZaZNGrU+jSKwXd8BgNnA6gO91SnrpspHyBt+Ngi4Nv9lyN3agcE/wWUkVWDoADBvpW/wlHrcN4tb2ocpN0QHjMCPehCpQxc6CRcD7E3cNFwsppYLFLu1f/4SU9xaX3U4Eo/jZgYEim6o2EO4gc80EXYM/XNZpgd1b4upiSsAIxppDERp7Z4GKR82dVCTKBULwKeqmrfr+Du9DhDw4ppVXv7BNCNOHJWhEmS+oTUDJuvDqUcn0/7xMcEROMGZynhHPdw0TOlDMM1BuQAC088fx3nDJBlriTvU3F8xbbHINz06YTG2kaYFjfeK4XM4aPCI1PodNvuytrS6Z+cjePhJsmdeHsD1zmR/MY3Y
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
