apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloakx
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: keycloakx
    server: 'https://kubernetes.default.svc'
  project: default
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/keycloakx
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/capi-staging/argocd-apps/keycloakx.yaml
    - repoURL: https://github.com/nihaldivyam/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - ApplyOutOfSyncOnly=true
    - CreateNamespace=true
