---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgBTM12fm/n4xcXCRYCwNiWBKyEjZMKq1jK5Ay5VEHLhqUj/qUIhGH8HmuXAtq0ymE2iaD28wYnrKtzgz3HsPNNTUJVtzJETWMj8+QI0wryf898juyNISyIKE0x4cbIlYLsLy9wH+3k8enB+t1fhliT3irYJ0fatr8kqN+vdrzffMYRGLRs2rHGmOZbz6ozx2JNakYjmKubWoCgDbG/nmmHoQluUzMedTFOvkGbeoS/16ysFMjEHA5+wk8bDHrmcKrNRgQuRjPPYF4GpBZfmcVsiVN0cVS4lW6s0YPelSNkpnWM1I2XpEPbpO2s1nJmPNJMJXkhiZ6UVL1f4ZW5bs/oy+jBkUtp5jIplCYLBb4PZqCWobEShRSH1l3pYLOT+/tEUz2ISQgSVUVJhIMzU2LTwiG8EHaec1xhrFMVYwvJrsTmor3Jv7cMTX8H+wax+BHMpunL70yAHQUkMHOfFjuExxZnK9NyaTg/tH5bD0DA/oU00MDn+OI594IQCINiKEA3SnVV3WyD2z8pE2GO8ogSlmBptiCxD2aXVE+HSCA/Wqhy/+I8yV7752D4YdlJ+OO32JOalEGuC9rGhbpwacg1vfOf+teaxn027qEXFySk5aPVlwnsXdHU7+V1OGTUUpJ9QrAYQDD+rCfP9ZJKIUPDDigJGodyx7udIDT1pIrupzm+4QYGS+5eD2OMS1BiGVpK00kqZGCeqHWHFL3Wk1aKP5JU8v+Q8PXzqIJzDAdUxdEaqVagPx3FqWuPonSUQEPzF6uCYFEXM6nKDaywzIFue
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
