apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argo-cd

spec:
  destination:
    namespace: cluster-autoscaler
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/cluster-autoscaler
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/guilherme-testing/argocd-apps/cluster-autoscaler.values.yaml
    - repoURL: https://github.com/guilherme-santos03/kubeaid-config-capi-test
      targetRevision: HEAD
      ref: values
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
