apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-configs
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    repoURL: https://github.com/guilherme-santos03/kubeaid-config-capi-test
    path: k8s/guilherme-testing/k8s-configs
    targetRevision: HEAD
    directory:
      recurse: true
