apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube2iam
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: aws
  project: default
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/kube2iam
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/guilherme-testing/argocd-apps/kube2iam.values.yaml
    - repoURL: https://github.com/guilherme-santos03/kubeaid-config-capi-test
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
