apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-operator
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: postgres-operator
  project: default
  sources:
    - repoURL: https://github.com/blackwoodseven/k8id.git
      path: argocd-helm-charts/postgres-operator
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/guilherme-testing/argocd-apps/values-postgres-operator.yaml
    - repoURL: https://github.com/guilherme-santos03/kubeaid-config-capi-test
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
    - CreateNamespace=true