apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd
  project: default
  source:
    path: k8s/guilherme-testing/argocd-apps
    repoURL: https://github.com/guilherme-santos03/kubeaid-config-capi-test
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
