apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argo-cd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  sources:
    - repoURL: https://github.com/Obmondo/KubeAid
      path: argocd-helm-charts/sealed-secrets
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/guilherme-testing/argocd-apps/sealed-secrets.values.yaml
    - repoURL: https://github.com/guilherme-santos03/kubeaid-config-capi-test
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
