global:
  clusterName: capi-staging
  customerid: bw7
  kubernetes:
    version: v1.31.0
  clusterAPI:
    version: v1.8.1
  capa:
    version: v2.6.1
    autoScaler: true
  kubeaid:
    repo: https://github.com/Obmondo/kubeaid
  kubeaidConfig:
    repo: https://github.com/nihaldivyam/kubeaid-config

provider:
  aws: true

aws:
  secretName: cloud-credentials
  sshKeyName: CapiStaging
  region: eu-west-1
  bastion:
    enabled: true
  vpc:
    cidrBlock: 10.14.0.0/22
  pods:
    cidrBlock: 10.244.0.0/16
  controlPlane:
    loadBalancer:
      loadBalancerType: nlb
    region: eu-west-1
    replicas: 3
    instanceType: t4g.medium
    ami:
      id: ami-09615cf870bc4ba4d
  machinePools:
    - name: nodes-a
      minSize: 1
      maxSize: 5
      replicas: 4
      labels:
        node.cluster.x-k8s.io/instancegroup: nodes-a
        node.cluster.x-k8s.io/usage: default-apps
        node.cluster.x-k8s.io/cluster-autoscaler-enabled: ""
        node.cluster.x-k9s.io/cluster-autoscaler-k8s.staging.blackwoodseven.com: ""
      instanceType: t4g.large
      ami:
        id: ami-09615cf870bc4ba4d
