---
keycloakx:
  dbchecker:
    enabled: true
  # ingress:
  #   enabled: true
  #   hosts:
  #     - keycloak.capistaging.bw7.io
  #   annotations:
  #     cert-manager.io/cluster-issuer: letsencrypt
  #   rules:
  #     - host: keycloak.staging.bw7.io
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #   tls:
  #     - secretName: keycloak-ssl
  #       hosts:
  #         - keycloak.staging.bw7.io
  database:
    vendor: postgres
    hostname: keycloakx-pgsql
    port: 5432
    database: keycloak
  extraEnv: |
    - name: KEYCLOAK_ADMIN
      value: admin
    - name: KC_LOG_LEVEL
      value: WARN
    - name: KC_DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: keycloak.keycloakx-pgsql.credentials.postgresql.acid.zalan.do
          key: username
    - name: KC_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: keycloak.keycloakx-pgsql.credentials.postgresql.acid.zalan.do
          key: password
    - name: KEYCLOAK_ADMIN_PASSWORD	
      valueFrom:	
        secretKeyRef:	
          key: KEYCLOAK_PASSWORD	
          name: keycloak-admin	
    - name: JAVA_OPTS_APPEND	
      value: '-Djgroups.dns.query=keycloakx-headless'
  extraInitContainers: |
    - name: custom-theme-provider
      image: 438423213058.dkr.ecr.eu-west-1.amazonaws.com/blackwoodseven/keycloak-theme:latest
      imagePullPolicy: IfNotPresent
      command:
        - sh
      args:
        - -c
        - |
          echo "Copying theme..."
          cp -R /bw7/* /theme
      volumeMounts:
        - name: theme
          mountPath: /theme    
  extraVolumeMounts: |
    - name: theme
      mountPath: /opt/keycloak/themes/bw7
  extraVolumes: |
    - name: theme
      emptyDir: {}
postgresql:
  enabled: true