---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: kube-system
spec:
  encryptedData:
    hcloud: AgCXLjL4ixRptNZEtBb9c6JCVdwBKUvFNUzX3Htb2g2t7Z5DeQKxh6LbAtqrPegUumYEo/LW0s0RbZK/npRrWtl+3j5wtIeBagyvSg6vptryEgkJgZiBf2hHA02o8bDBJNXzgXuylOeRKXV5qSXepy7xSO2bBExYFFB6/FTv2BqQrGLUDWjj96v8nL3EoKUM5Y5p5VRqRmunTHeAuxaZYAzLJkBbDxPvvR2pTwKzGxjiiCTEwLvCHWU4hWCHRgKamJZtgVX3pXlnBJs8zH1zHUi35XFgthIszwBbwCp5lh8wT1gFLiWpmW17B2OCuqxDpU7+W6eDeg0fktSS2MAFA5NF+a2X73em/g7aw0ElqKPK3t9J9y/OQA3zftQZWHs9zMExeiZA1/NQxkHgEPiubej4L0yO8Gnm4EOlBfYz5qNsX5yvZ+5lLbbAiXE9hglaHubIPeGclRXJjgjvTExQPdqu8F9gYA2kwcri88Tz0oROD+FzpeGFql8CyM22ur5PusGiOKyh//eS92c33MFEHPdsEaKr4YS84Qc7Mfpq6xOiU25+jJUDhGTi4gv2coi+p8MJHZSI9B2oF3BHzGwe9q/rFwDCfKvS73Kh27BzEHNy50idtNOxYTqCGIbZcGgrYy5FGIY4H6QJfkB79NBaZKFosPdOtB0e17nyM2B6Z0FFl3UzUUwMeh8g5dMlFrzBfJEn8v+z2TsB82CrtG8MYElQdmUaSRCqLFmnjVJt4zrS+4aBlTfkoZfj2PN3lr/ch5kvPEkCBOwrQG071aboPrS8
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: kube-system
