global:
  clusterName: test.cluster.com
  customerid: kubeaid-demo
  kubernetes:
    version: v1.28.3
  clusterAPI:
    version: v1.8.1
  capa:
    version: v2.6.1
    autoScaler: true
  kubeaid:
    repo: https://github.com/Archisman-Mridha/kubeaid.git
  kubeaidConfig:
    repo: https://github.com/Archisman-Mridha/kubeaid-config.git

provider:
  aws: true

aws:
  secretName: capi-cluster-token
  sshKeyName: kubeaid-demo
  region: eu-west-1
  bastion:
    enabled: true
  vpc:
    cidrBlock: 10.14.0.0/22
  pods:
    cidrBlock: 10.244.0.0/16
  controlPlane:
    loadBalancerType: nlb
    region: eu-west-1
    replicas: 3
    instanceType: t3a.large
    ami:
      id: ami-03cd26c84ae9a587c
  workerNodes:
    region: eu-west-1
    replicas: 2
    instanceType: t3a.large
    ami:
      id: ami-03cd26c84ae9a587c
