---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: capi-cluster
spec:
  encryptedData:
    hcloud: AgBDixiL0hFTbs7XWirHoG24elEttP8oPBbxZtT4FBfGJ+o0zDOpR3TN/OwR4DGG3T0eK6fOvMPwJZ2+C8ndhBpK7kEimnLYZ1ce9QBczesw+r3M0bVm7giGyqZTdwzIHrZS3/54SxYjHyugtZNeWmfsIUydKZT2USPj+VsmL+mDWVzj6keZsAjDqFJ4Vx47tJ2weaRPVV/ptRsQsuoCz37kQMdz0MJ7tqVcNWxVAhmU3Duxlk/b74EYOAXSPIITm/zTSA2bXIWUbEhs/bJOKZveZLgCeu13gW9X1Lw9wJjaxRvEhXuP3s3W35Gf1+q7zRGX5mDhImKZN16VmTGq4btTYsoPs5rWfZcI0V+iYRftnA1aZpoPbbUDhXC2y/UuSVo+8DGtscULcJXsAC+MJxCv42CioBFlud6bJm094mAv/NakJZCtaRPQONmNIJSHa1Gz7Od+Bx8P4mjmVOwmfbjf2el36ktbIL/Ztg/Om/0CQC+AlxaUd/OJ3B44kAC0EKxyumEkpd4yXtulGZ3WpyYFwzlKsTLtvk4TOe2yvWr/KnijqBPphQHmmISqTzKft+2fX4+pRFKdbpQpf4Ur9msJ6Zx8l+gDolqurhF9XoN031iid/4ZBCCSUmZBOEgdp6hhsGqihCeVxAJNpiuSKBoaDze9EWYQO2G+Moyiqu4Gn+UXyMnNs4D+Ku7g67uffriakABMvTGyU1VKhwFdZcByK5LNvFndmffgjOMs6t/QciHQxvh4bfTo3SwaSzwqH/sFrOpgvfZKs53zJ/yI/5sz
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: capi-cluster
