global:
  clusterName: guilherme-ssh
  kubernetes:
    version: v1.31.0
  clusterAPI:
    version: v1.8.1
  capa:
    version: v2.6.1
    autoScaler: true
  kubeaid:
    repo: https://github.com/Obmondo/KubeAid
  kubeaidConfig:
    repo: https://github.com/guilherme-santos03/kubeaid-config-capi-test

provider:
  aws: true

aws:
  secretName: cloud-credentials
  sshKeyName: guilherme-ssh
  region: eu-west-1
  bastion:
    enabled: true
  vpc:
    cidrBlock: 10.14.0.0/22
  pods:
    cidrBlock: 10.244.0.0/16
  controlPlane:
    loadBalancer:
      loadBalancerType: nlb
    region: eu-west-1
    replicas: 1
    instanceType: t4g.medium
    ami:
      id: ami-09615cf870bc4ba4d
  machinePools:
    - name: nodes-guilherme
      ami: ami-09615cf870bc4ba4d
      instanceType: t4g.medium
      labels:
        node.cluster.x-k8s.io/instancegroup: nodes-guilherme
        node.cluster.x-k8s.io/usage: guilherme
      replicas: 2
      rootVolumeSize: 75
      sshKeyName: guilherme-ssh
    - name: nodes-guilherme2
      ami: ami-09615cf870bc4ba4d
      instanceType: t4g.small
      labels:
        node.cluster.x-k8s.io/instancegroup: nodes-guilherme-tainted
        node.cluster.x-k8s.io/usage: guilherme-tainted
      replicas: 1
      rootVolumeSize: 75
      sshKeyName: guilherme-ssh
      taints:
        - key: "dedicated"
          value: "guilherme-taint"
          effect: "NoSchedule"
