apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets
  namespace: argo-cd

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    path: k8s/guilherme-test/sealed-secrets
    repoURL: https://github.com/guilherme-santos03/kubeaid-config-capi-test
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy: {}
